---

- name: >-
    Ensure {{ vector_service }}
    is enabled: {{ vector_service_enable }}
    and state: {{ vector_service_ensure }}
  service:
    name: "{{ vector_service }}"
    enabled: "{{ vector_service_enable }}"
    state: "{{ vector_service_ensure }}"
  become: true
  register: service_result

- name: Vector | Debug service result
  debug:
    var: service_result
  when: service_result is failed
