---
- name: Vector | Restart service
  # become: true
  # ansible.builtin.service:
  #   name: vector
  #   state: restarted
  set_fact:
    vector_service_ensure: "restarted"
  listen: 'restart-vector'
